name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
     - run: echo "hi there"
     - uses: actions/checkout@v6
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '20.x'
     
     # Клиент
     - name: Install client dependencies
       run: npm ci
       working-directory: client

     - name: Lint client
       run: npx eslint src
       working-directory: client
